--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/04/2021 13:00:32
-- Server version: 5.5.5-10.4.10-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE bddemobbva;

--
-- Drop table `preferencia`
--
DROP TABLE IF EXISTS preferencia;

--
-- Drop table `producto`
--
DROP TABLE IF EXISTS producto;

--
-- Drop table `tipoproducto`
--
DROP TABLE IF EXISTS tipoproducto;

--
-- Drop table `usuario`
--
DROP TABLE IF EXISTS usuario;

--
-- Set default database
--
USE bddemobbva;

--
-- Create table `usuario`
--
CREATE TABLE usuario (
  idusuario int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(100) DEFAULT NULL,
  dni varchar(8) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  contraseña varchar(45) DEFAULT NULL,
  telefono varchar(20) DEFAULT NULL,
  fechanacimiento varchar(45) DEFAULT NULL,
  PRIMARY KEY (idusuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tipoproducto`
--
CREATE TABLE tipoproducto (
  idtipoproducto int(11) NOT NULL AUTO_INCREMENT,
  descripcion varchar(100) DEFAULT NULL,
  PRIMARY KEY (idtipoproducto)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `producto`
--
CREATE TABLE producto (
  idproducto int(11) NOT NULL AUTO_INCREMENT,
  nombreproducto varchar(100) DEFAULT NULL,
  tipoproducto varchar(45) DEFAULT NULL,
  PRIMARY KEY (idproducto)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `preferencia`
--
CREATE TABLE preferencia (
  idpreferencia int(11) NOT NULL AUTO_INCREMENT,
  descripcion varchar(100) DEFAULT NULL,
  idusuario int(11) DEFAULT NULL,
  PRIMARY KEY (idpreferencia)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table usuario
--
INSERT INTO usuario VALUES
(1, 'Aguayo González\tJaime Francisco', '36142578', 'maeillanes@hotmail.com', 'yropeniati', '8838144031', '21-02-1966'),
(2, 'Andrea Chávez Heredia ', '45142578', 'osabarca@hotmail.com', 'lawarbonfi', '6425684410', '11-10-1951'),
(3, 'Ruth Silvana Cortés Lagunes', '36142438', 'vizkala@hotmail.com', 'diondigalc', '8484887067', '10-03-1949'),
(4, 'Luis Felipe  Delgado Barrón', '36155578', 'capitanaguilera@hotmail.com', 'tecturvahe', '6580740361', '15-04-1943'),
(5, 'Hansel Andres Espejo Ramos', '44142578', 'mapuchin@hotmail.com', 'likeyarkso', '8501497227', '09-02-1940'),
(6, 'Gara Uriarte Modino', NULL, 'bad.girl.-@hotmail.es', NULL, NULL, NULL),
(7, 'Drucila Hortiz Nanclares', NULL, 'aargomedo@hecsa.cl', NULL, NULL, NULL),
(8, 'Valeria Obana Camacho', NULL, 'c_arnes@hotmail.com', NULL, NULL, NULL),
(9, 'Valeria Obana Camacho', NULL, 'arquitectoasenjo@gmail.com', NULL, NULL, NULL),
(10, 'Luarana Losua Muro', NULL, 'aargomedo@hecsa.cl', NULL, NULL, NULL);

-- 
-- Dumping data for table tipoproducto
--
-- Table bddemobbva.tipoproducto does not contain any data (it is empty)

-- 
-- Dumping data for table producto
--
-- Table bddemobbva.producto does not contain any data (it is empty)

-- 
-- Dumping data for table preferencia
--
-- Table bddemobbva.preferencia does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;